### ISSUE TITLE
Suggestion: count how many variants user has, and if they have all known variants, indicate that fact

### ISSUE THREAD

**Issue by supersandra** [EhsanKia/CatalogScanner#5]
I see the technical limitation for why CatalogScanner can't get the specific variant information, but I was wondering if it could detect when someone has ALL of them, so various services could potentially do something with that data. Not sure if it's too hard to count the little dots, but... :)

**Comment by EhsanKia** [comment]
That's not doable either, since you're scrolling by page and not items. The technical limitations is not in reading the text, it's in the recording. The Switch only lets you record in 30s increments, and for a long list, it can take many videos to scroll through and it's hard to even tell when the 30s is over.

**Comment by supersandra** [comment]
Ah, that makes sense! Alas. Thanks for the reply! :)
